# config/train_config.yaml

experiment:
  exp_name: "exp03_cube_structure_v1"  # 修改这里开启新实验
  exp_description: "稳健训练：长 KL warmup，判别器在 warmup 后开启"
  save_dir: "./experiments"

data:
  data_root: "/chendou_space/data/aligned_Training_Data" # 你的数据文件夹路径
  file_extension: ".npy"               # 假设你的数据存为 npy，如果是 bin 请自行调整
  image_size: 256
  croped_size: 128                    # 请确认：如果想裁 128^3，改为 128，并调整 batch_size
  channels: 1
  num_workers: 24                      # 利用你的 96 核 CPU

model:
  base_channels: 64                    # 基础通道数，越大模型越宽，显存占用越高
  ch_mult: [1, 2, 2, 4]                # 下采样倍率，256 -> 128 -> 64 -> 32 (Latent大小 32x32x32)
  num_res_blocks: 1
  z_channels: 4                        # Latent 的通道数 (最终压缩为 4x32x32x32)
  
loss:
  kl_weight: 1e-6                  # KL 散度的权重，初期要小，避免后验坍塌
  disc_weight: 0.0035                     # 对抗损失权重
  disc_start: 22001                     # 多少步之后开启判别器 (Warmup)

train:
  seed: 42
  batch_size: 2                        # A100 80G 上 256^3 数据，建议从 2 开始尝试，甚至可以试 4
  epochs: 500
  lr: 1.3e-4   # 4.5e-6 * batch_size? 通常 1e-4 是个好的起点
  log_interval: 1                     # 多少个 batch 打印一次日志
  save_interval: 2                     # 多少个 epoch 保存一次模型
  kl_warmup_steps: 20000               # KL 散度的 Warmup 步数